[package]
name = "rust-signal-handling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 在Cargo.toml文件中加入Tokio依赖项：
tokio = { version="1.25.0", features=["full"] }
