[package]
name = "wasm-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
js-sys = "0.3.68"
wasm-bindgen = "0.2.91"


[lib]
crate-type = ["cdylib"]