[package]
name = "RTC-remoc-example"
version = "0.1.0"
edition = "2021"

[dependencies]
remoc = "0.13.0"
futures = "0.3"
tokio = {version = "1.38.0", features = ["full"]}
serde = { version = "1.0", features = ["derive"] }