[package]
name = "rust-sqlx-sqlite"
version = "0.1.0"
edition = "2021"


[dependencies]
sqlx ={ version = "0.7.3", features = ["runtime-async-std-native-tls", "sqlite"]}
async-std ={ version = "1.6", features = ["attributes"]}
futures = "0.3.18"